packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  - "@oxlint-tsgolint/darwin-arm64@7.0.2002"
  - "@oxlint-tsgolint/darwin-x64@7.0.2002"
  - "@oxlint-tsgolint/linux-arm64@7.0.2002"
  - "@oxlint-tsgolint/linux-x64@7.0.2002"
  - "@oxlint-tsgolint/win32-arm64@7.0.2002"
  - "@oxlint-tsgolint/win32-x64@7.0.2002"
  - oxlint-tsgolint@7.0.2002
